"""Initial schema — users, research_sessions, sources, knowledge_documents,
reports, agent_logs, user_settings

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-22 00:00:00

Hand-written to match backend/models/*.py exactly (rather than
autogenerated against a live DB), so this can be reviewed and committed
without requiring a running Postgres instance first.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("clerk_id", sa.String(255), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("avatar_url", sa.String(1024), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "member", "viewer", name="user_role"),
            nullable=False,
            server_default="member",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("research_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_users_clerk_id", "users", ["clerk_id"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ── research_sessions ────────────────────────────────────────────────
    op.create_table(
        "research_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "planning", "researching", "extracting", "verifying",
                "summarizing", "writing_report", "generating_executive_summary",
                "generating_citations", "exporting_pdf", "completed", "failed",
                name="session_status",
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("research_plan", postgresql.JSONB(), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_research_sessions_user_id", "research_sessions", ["user_id"])
    op.create_index("ix_research_sessions_status", "research_sessions", ["status"])

    # ── sources ──────────────────────────────────────────────────────────
    op.create_table(
        "sources",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "research_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("research_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("url", sa.String(2048), nullable=False),
        sa.Column("title", sa.String(512), nullable=True),
        sa.Column("domain", sa.String(255), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("extracted_content", sa.Text(), nullable=True),
        sa.Column("domain_authority_score", sa.Float(), nullable=True),
        sa.Column("source_age_score", sa.Float(), nullable=True),
        sa.Column("citation_count_score", sa.Float(), nullable=True),
        sa.Column("trustworthiness_score", sa.Float(), nullable=True),
        sa.Column("verification_notes", postgresql.JSONB(), nullable=True),
        sa.Column("published_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("citation_index", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_sources_research_session_id", "sources", ["research_session_id"])
    op.create_index("ix_sources_domain", "sources", ["domain"])

    # ── knowledge_documents ──────────────────────────────────────────────
    op.create_table(
        "knowledge_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "research_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("research_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "source_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sources.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chroma_vector_id", sa.String(255), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("metadata_tags", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index(
        "ix_knowledge_documents_chroma_vector_id", "knowledge_documents", ["chroma_vector_id"], unique=True
    )
    op.create_index("ix_knowledge_documents_research_session_id", "knowledge_documents", ["research_session_id"])
    op.create_index("ix_knowledge_documents_source_id", "knowledge_documents", ["source_id"])
    op.create_index("ix_knowledge_documents_user_id", "knowledge_documents", ["user_id"])

    # ── reports ──────────────────────────────────────────────────────────
    op.create_table(
        "reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "research_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("research_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(512), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("introduction", sa.Text(), nullable=True),
        sa.Column("key_findings", sa.Text(), nullable=True),
        sa.Column("analysis", sa.Text(), nullable=True),
        sa.Column("recommendations", sa.Text(), nullable=True),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column("short_summary", sa.Text(), nullable=True),
        sa.Column("medium_summary", sa.Text(), nullable=True),
        sa.Column("detailed_summary", sa.Text(), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("key_takeaways", postgresql.JSONB(), nullable=True),
        sa.Column("risks", postgresql.JSONB(), nullable=True),
        sa.Column("opportunities", postgresql.JSONB(), nullable=True),
        sa.Column("citations_apa", postgresql.JSONB(), nullable=True),
        sa.Column("citations_mla", postgresql.JSONB(), nullable=True),
        sa.Column("citations_ieee", postgresql.JSONB(), nullable=True),
        sa.Column(
            "default_citation_style",
            sa.Enum("apa", "mla", "ieee", name="citation_style"),
            nullable=False,
            server_default="apa",
        ),
        sa.Column("pdf_file_path", sa.String(1024), nullable=True),
        sa.Column("pdf_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chart_data", postgresql.JSONB(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_reports_research_session_id", "reports", ["research_session_id"], unique=True)
    op.create_index("ix_reports_user_id", "reports", ["user_id"])

    # ── agent_logs ───────────────────────────────────────────────────────
    op.create_table(
        "agent_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "research_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("research_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "agent_name",
            sa.Enum(
                "research_coordinator", "web_research", "content_extraction",
                "fact_verification", "knowledge_base", "summarization",
                "report_writer", "citation", "executive_summary", "pdf_generation",
                name="agent_name",
            ),
            nullable=False,
        ),
        sa.Column(
            "level",
            sa.Enum("info", "warning", "error", "success", name="log_level"),
            nullable=False,
            server_default="info",
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_agent_logs_research_session_id", "agent_logs", ["research_session_id"])
    op.create_index("ix_agent_logs_agent_name", "agent_logs", ["agent_name"])
    op.create_index("ix_agent_logs_created_at", "agent_logs", ["created_at"])

    # ── user_settings ────────────────────────────────────────────────────
    op.create_table(
        "user_settings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("openrouter_key_encrypted", sa.String(1024), nullable=True),
        sa.Column("groq_key_encrypted", sa.String(1024), nullable=True),
        sa.Column("tavily_key_encrypted", sa.String(1024), nullable=True),
        sa.Column("preferred_model", sa.String(255), nullable=True),
        sa.Column("default_max_sources", sa.Integer(), nullable=False, server_default="10"),
        sa.Column("default_citation_style", sa.String(16), nullable=False, server_default="apa"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_user_settings_user_id", "user_settings", ["user_id"], unique=True)


def downgrade() -> None:
    op.drop_table("user_settings")
    op.drop_table("agent_logs")
    op.drop_table("reports")
    op.drop_table("knowledge_documents")
    op.drop_table("sources")
    op.drop_table("research_sessions")
    op.drop_table("users")

    # Enum types created implicitly by the columns above must be dropped
    # explicitly on downgrade (Postgres doesn't cascade-drop custom types).
    for enum_name in (
        "citation_style", "log_level", "agent_name",
        "session_status", "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
